export const site = {
  name: "Mr. Drain Plumber",
  tagline: "Saskatoon's straight-talking plumbers",
  phone: "639-307-3028",
  phoneHref: "tel:+16393073028",
  email: "info@mrdrainsk.com",
  emailHref: "mailto:info@mrdrainsk.com",
  addressLine: "147 Dagnone Ln, Saskatoon, SK S7V 0R1",
  hours: "24/7 Emergency Line",
  yearsInBusiness: 8,
  foundedYear: 2018,
  serviceCities: [
    "Saskatoon",
    "Brighton",
    "Rosewood",
    "Stonebridge",
    "College Park",
    "Martensville",
    "Warman",
  ],
} as const;
