export const site = {
  name: "Mr. Drain Plumber",
  tagline: "Saskatoon's straight-talking plumbers",
  phone: "(306) 555-0142",
  phoneHref: "tel:+13065550142",
  email: "info@mrdrainsk.com",
  emailHref: "mailto:info@mrdrainsk.com",
  addressLine: "PLACEHOLDER — 1425 8th Street E, Saskatoon, SK S7H 0S6",
  hours: "24/7 Emergency Line",
  yearsInBusiness: 8,
  foundedYear: 2018,
  serviceCities: [
    "Saskatoon",
    "Brighton",
    "Rosewood",
    "Stonebridge",
    "College Park",
    "Martensville",
    "Warman",
  ],
} as const;
